### ISSUE TITLE
Can not run sample 

### ISSUE THREAD

**Issue by MrThiago** [flurry/YodelAndroidApp#2]
C:\Programming\2-SDKs\Flurry Android SDK vAndroid SDK 6.0.0\Android 6.0.0\SAMPLE\YodelAndroidApp-master\yodel-sample\build\intermediates\exploded-aar\com.yahoo.mobile.client.share.search\YahooSearch-0.1.0-with-volley\res\drawable-hdpi\yssdk_yahoo_attribution_logo.png
Error:Error: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Programming\skd\build-tools\build-tools-21.1.2\aapt.exe'' finished with non-zero exit value 42
:yodel-sample:mergeDebugResources FAILED
Error:Execution failed for task ':yodel-sample:mergeDebugResources'.

> C:\Programming\2-SDKs\Flurry Android SDK vAndroid SDK 6.0.0\Android 6.0.0\SAMPLE\YodelAndroidApp-master\yodel-sample\build\intermediates\exploded-aar\com.yahoo.mobile.client.share.search\YahooSearch-0.1.0-with-volley\res\drawable-hdpi\yssdk_yahoo_attribution_logo.png: Error: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Programming\skd\build-tools\build-tools-21.1.2\aapt.exe'' finished with non-zero exit value 42

**Comment by ugonna** [comment]
This is likely because your path names are too long for Windows to process. The resource that gradle is trying to merge is in a path `C:\Programming\2-SDKs\Flurry Android SDK vAndroid SDK 6.0.0\Android 6.0.0\SAMPLE\YodelAndroidApp-master\yodel-sample\build\intermediates\exploded-aar\com.yahoo.mobile.client.share.search\YahooSearch-0.1.0-with-volley\res\drawable-hdpi\yssdk_yahoo_attribution_logo.png` which is 267 characters long. 

The Windows [limit is 260](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#maxpath).

You can shorten the path name by storing the project elsewhere and try again.

If that doesn't work, run `gradlew.bat assembleDebug --info` on that path in your command prompt to see what the exact issue is.
